package org.com.pojo;
// Generated 25 Apr, 2015 7:30:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BarcodeTable generated by hbm2java
 */
@Entity
@Table(name="barcode_table"
    ,catalog="bsale"
)
public class BarcodeTable  implements java.io.Serializable {


     private Integer bid;
     private String bno;
     private int lid;
     private int pid;

    public BarcodeTable() {
    }

    public BarcodeTable(String bno, int lid, int pid) {
       this.bno = bno;
       this.lid = lid;
       this.pid = pid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Bid", unique=true, nullable=false)
    public Integer getBid() {
        return this.bid;
    }
    
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    
    @Column(name="Bno", nullable=false, length=10)
    public String getBno() {
        return this.bno;
    }
    
    public void setBno(String bno) {
        this.bno = bno;
    }

    
    @Column(name="Lid", nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }

    
    @Column(name="Pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }




}


