package org.com.pojo;
// Generated 25 Apr, 2015 7:30:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ctype generated by hbm2java
 */
@Entity
@Table(name="ctype"
    ,catalog="bsale"
)
public class Ctype  implements java.io.Serializable {


     private Integer cid;
     private String ctype;
     private Float disc;

    public Ctype() {
    }

    public Ctype(String ctype, Float disc) {
       this.ctype = ctype;
       this.disc = disc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cid", unique=true, nullable=false)
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    
    @Column(name="ctype")
    public String getCtype() {
        return this.ctype;
    }
    
    public void setCtype(String ctype) {
        this.ctype = ctype;
    }

    
    @Column(name="disc", precision=100, scale=0)
    public Float getDisc() {
        return this.disc;
    }
    
    public void setDisc(Float disc) {
        this.disc = disc;
    }




}


