package org.com.pojo;
// Generated 25 Apr, 2015 7:30:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductTable generated by hbm2java
 */
@Entity
@Table(name="product_table"
    ,catalog="bsale"
    , uniqueConstraints = @UniqueConstraint(columnNames="Pname") 
)
public class ProductTable  implements java.io.Serializable {


     private Integer pid;
     private String pname;
     private String category;
     private String author;
     private String publisher;
     private String quantity;
     private BigDecimal pprice;
     private BigDecimal sprice;
     private int rackno;
     private String isbn;

    public ProductTable() {
    }

	
    public ProductTable(String pname, String category, BigDecimal pprice, int rackno) {
        this.pname = pname;
        this.category = category;
        this.pprice = pprice;
        this.rackno = rackno;
    }
    public ProductTable(String pname, String category, String author, String publisher, String quantity, BigDecimal pprice, BigDecimal sprice, int rackno, String isbn) {
       this.pname = pname;
       this.category = category;
       this.author = author;
       this.publisher = publisher;
       this.quantity = quantity;
       this.pprice = pprice;
       this.sprice = sprice;
       this.rackno = rackno;
       this.isbn = isbn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Pid", unique=true, nullable=false)
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    
    @Column(name="Pname", unique=true, nullable=false, length=50)
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }

    
    @Column(name="Category", nullable=false, length=50)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="author", length=100)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="publisher", length=100)
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    
    @Column(name="Quantity", length=50)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="PPrice", nullable=false, precision=50)
    public BigDecimal getPprice() {
        return this.pprice;
    }
    
    public void setPprice(BigDecimal pprice) {
        this.pprice = pprice;
    }

    
    @Column(name="SPrice", precision=50)
    public BigDecimal getSprice() {
        return this.sprice;
    }
    
    public void setSprice(BigDecimal sprice) {
        this.sprice = sprice;
    }

    
    @Column(name="Rackno", nullable=false)
    public int getRackno() {
        return this.rackno;
    }
    
    public void setRackno(int rackno) {
        this.rackno = rackno;
    }

    
    @Column(name="isbn", length=50)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }




}


