package org.com.pojo;
// Generated 25 Apr, 2015 7:30:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stockin generated by hbm2java
 */
@Entity
@Table(name="stockin"
    ,catalog="bsale"
)
public class Stockin  implements java.io.Serializable {


     private Integer stiid;
     private int pid;
     private int lid;
     private int bno;
     private Date date;

    public Stockin() {
    }

    public Stockin(int pid, int lid, int bno, Date date) {
       this.pid = pid;
       this.lid = lid;
       this.bno = bno;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Stiid", unique=true, nullable=false)
    public Integer getStiid() {
        return this.stiid;
    }
    
    public void setStiid(Integer stiid) {
        this.stiid = stiid;
    }

    
    @Column(name="Pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }

    
    @Column(name="Lid", nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }

    
    @Column(name="Bno", nullable=false)
    public int getBno() {
        return this.bno;
    }
    
    public void setBno(int bno) {
        this.bno = bno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


