package org.com.pojo;
// Generated 25 Apr, 2015 7:30:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stockout generated by hbm2java
 */
@Entity
@Table(name="stockout"
    ,catalog="bsale"
)
public class Stockout  implements java.io.Serializable {


     private Integer stoid;
     private String lid;
     private Integer bno;
     private int pid;
     private int invno;
     private Date date;

    public Stockout() {
    }

	
    public Stockout(int pid, int invno) {
        this.pid = pid;
        this.invno = invno;
    }
    public Stockout(String lid, Integer bno, int pid, int invno, Date date) {
       this.lid = lid;
       this.bno = bno;
       this.pid = pid;
       this.invno = invno;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Stoid", unique=true, nullable=false)
    public Integer getStoid() {
        return this.stoid;
    }
    
    public void setStoid(Integer stoid) {
        this.stoid = stoid;
    }

    
    @Column(name="Lid", length=10)
    public String getLid() {
        return this.lid;
    }
    
    public void setLid(String lid) {
        this.lid = lid;
    }

    
    @Column(name="Bno")
    public Integer getBno() {
        return this.bno;
    }
    
    public void setBno(Integer bno) {
        this.bno = bno;
    }

    
    @Column(name="Pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }

    
    @Column(name="Invno", nullable=false)
    public int getInvno() {
        return this.invno;
    }
    
    public void setInvno(int invno) {
        this.invno = invno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


