package org.com.pojo;
// Generated 25 Apr, 2015 7:30:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usertab generated by hbm2java
 */
@Entity
@Table(name="usertab"
    ,catalog="bsale"
)
public class Usertab  implements java.io.Serializable {


     private Integer id;
     private String uid;
     private String pass;
     private String status;
     private String ps;

    public Usertab() {
    }

	
    public Usertab(String uid, String pass) {
        this.uid = uid;
        this.pass = pass;
    }
    public Usertab(String uid, String pass, String status, String ps) {
       this.uid = uid;
       this.pass = pass;
       this.status = status;
       this.ps = ps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid", nullable=false, length=20)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="pass", nullable=false)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="ps", length=20)
    public String getPs() {
        return this.ps;
    }
    
    public void setPs(String ps) {
        this.ps = ps;
    }




}


